### ISSUE TITLE
"fancyPlaceAnimation" doesn't work and mod compatibility problem

### ISSUE THREAD

**Issue by Thunder-Power** [Hantonik/FancyBlockParticles#1]
### Issue description:

1.Putting blocks in the worlds after "fancyPlaceAnimation" is true in the mod options has no corresponding effect.
2.Also found when "SereneSeasons mod" works with FBP will crash the game after start.

### Steps to reproduce:

none

### FBP version:

1.0.2.4

### Minecraft version:

1.20.4

### Modloader:

Fabric

### Modloader version:

0.15.6

### The latest.log file:

[latest.log](https://github.com/Hantonik/FancyBlockParticles/files/14318904/latest.log)

**Comment by Hantonik** [comment]
Hi, thanks for reporting these issues.
1. I'm still working on the placing animation feature, so it's not available yet.
2. I'm well on my way to fixing this bug.

**Comment by thrasos-dev** [comment]
+1 up on the placing animation feature.

**Comment by Mysticpasta1** [comment]
+1 for fancy block animation but for 1.19.2 forge
