### ISSUE TITLE
Loading error to enter minecraft

### ISSUE THREAD

**Issue by Angelox123** [Hantonik/FancyBlockParticles#12]
### Issue description:

![imagen_2024-05-22_125848881](https://github.com/Hantonik/FancyBlockParticles/assets/170561654/db9ce286-2ee3-4116-874a-768a20008d9b)
idk what to do, i like this mod so much (i play in 1.20.1, and i just open the minecraft only with this mod)

### Steps to reproduce:

1 Open minecraft (select mod before)
2 And just loading error

### FBP version:

1.1.2.0

### Minecraft version:

1.20.4

### Modloader:

Forge

### Modloader version:

Forge

**Comment by mintypoo** [comment]
Has this issue been resolved yet? I am currently experiencing the same issue!

**Comment by Hantonik** [comment]
Hi
Both versions 1.20.1 and 1.20.4 have been rewritten, so the bug should be resolved. Unfortunately, I can't confirm this precisely as the `latest.log` file wasn't attached.
