### ISSUE TITLE
[Bug] Flame Particles can't be disabled

### ISSUE THREAD

**Issue by QwertRvg** [Hantonik/FancyBlockParticles#19]
### Issue description:

If the config option for fancy flame particles is disabled, they still appear.
Not sure if it's because of another mod or not

### Steps to reproduce:

1. Disable the option
2. place fire / spawn a blaze
3. (again not sure if another mod is at fault here)

### FBP version:

20.1.0.0

### Minecraft version:

1.20.1

### Modloader version:

47.3.0

### The latest.log file:

[latest.log](https://github.com/user-attachments/files/15858027/latest.log)

**Comment by Hantonik** [comment]
Hi, thanks for the report!
However, it seems you might have chosen the wrong option, as neither fire nor blaze generate flame particles, but rather smoke particles. Flame particles are generated by blocks like furnace and torch.
You can disable smoke particles with the `Fancy smoke particles` option.

**Comment by QwertRvg** [comment]
oh my bad then
thanks a lot for clearing that up!
