### ISSUE TITLE
settings doesnt save

### ISSUE THREAD

**Issue by almighty-splinter** [Hantonik/FancyBlockParticles#2]
### Issue description:

the done button isnt showing below reload config

### Steps to reproduce:

.

### FBP version:

1.0.3.0-beta

### Minecraft version:

1.20.4

### Modloader:

Fabric

### Modloader version:

0.15.7

### The latest.log file:

.

**Comment by Hantonik** [comment]
Hi, the **done** and **reset** buttons are likely there, but they are below the screen due to its size.
Adjusting the **GUI Scale** to a smaller setting should make the buttons visible.

I'm currently working on scaling the **FBP Options Menu** to fit in the screen better.
