### ISSUE TITLE
[Bug][1.20.1] Incompatible with NeoForge due to Forge having a different version dependency.

### ISSUE THREAD

**Issue by VOLKOUL** [Hantonik/FancyBlockParticles#22]
### Issue description:

Won't launch on NeoForge 1.20.1
Crashes on startup.

### Steps to reproduce:

Launch game

### FBP version:

FBP-1.20.1-forge-20.1.0.1-beta

### Minecraft version:

1.20.1

### Modloader version:

NeoForge

**Comment by Iskaa303** [comment]
try using FBP version 1.1.2.0-beta

**Comment by Hantonik** [comment]
Hello,
Unfortunately NeoForge for Minecraft 1.20.1 is no longer supported in newer versions.
I recommend switching to Forge or Fabric, or updating to a newer version of Minecraft.
