### ISSUE TITLE
[Bug]  Creates Particles with No Texture

### ISSUE THREAD

**Issue by WHiZSTA** [Hantonik/FancyBlockParticles#23]
### Issue description:

Creates a bunch of particles with no textures when breaking vertical slabs/stairs etc from "Additional Placements" Something isn't mapping correctly.
![2024-06-26_13 55 26](https://github.com/Hantonik/FancyBlockParticles/assets/18521070/1422312e-1269-4055-8872-ad157d8f500e)

### Steps to reproduce:

[https://modrinth.com/mod/additional-placements-fabric](https://modrinth.com/mod/additional-placements-fabric)
1) place down a vertical slab (which inherit the normal slab/blocks's graphics)
2) break it from the side... from the top or bottom particles appear correctly

### FBP version:

20.1.0.2-beta

### Minecraft version:

1.20.1

### Modloader version:

Fabric 0.15.11

### The latest.log file:

No Logable Errors

**Comment by Marco6789** [comment]
Had this issue with another mod, Create: Copycats+. I cloned the code and fixed it locally by changing one line in MixinParticleEngine. In the `destroy()` method, near the top is the line `var sprite = Minecraft.getInstance().getBlockRenderer().getBlockModelShaper().getParticleIcon(state);`. However, `getParticleIcon()` is deprecated. I fixed the issue by replacing that part of the line with the `getTexture()` method. Though i'm not sure if that would fix the problem with additional placements, i think there's a good chance that it will.
