### ISSUE TITLE
[Bug] Visual Error when using with A Good Place mod

### ISSUE THREAD

**Issue by Iskaa303** [Hantonik/FancyBlockParticles#25]
### Issue description:

When using A Good Place mod with FancyBlockParticles, and then breaking the block, 3D particles are turning black

https://github.com/Hantonik/FancyBlockParticles/assets/72253984/e367e829-bb62-4b95-94ec-b5488b9dd339

### Steps to reproduce:

1. Install FancyBlockParticles, A Good Place mod
2. Run the game and create the world
3. Start breaking and placing blocks

### FBP version:

1.1.2.0-beta

### Minecraft version:

1.20.1

### Modloader version:

NeoForge 47.1.106

### The latest.log file:

[latest.log](https://github.com/user-attachments/files/16104159/latest.log)

**Comment by Mushroom6678** [comment]
personally i use embeddium and i dont seem to have any bugs so maybe try switching to embeddium as a temporary fix to this issue

**Comment by Hantonik** [comment]
Hi, thanks for your report.
Unfortunately, NeoForge for Minecraft 1.20.1 is **no longer supported**. From my tests, this issue doesn’t happen with other ModLoaders.
I recommend trying a different loader to fix the problem.
