### ISSUE TITLE
[Bug] neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Hantonik/FancyBlockParticles#33]
### Issue description:

modmenu mod and this mod causes this error 
![image](https://github.com/user-attachments/assets/8587bdc4-4f86-4eaf-92ea-fd6cc5c1d93f)

### Steps to reproduce:

add "mod menu" (the neoforge port) and the mod

### FBP version:

latest

### Minecraft version:

1.21

### Modloader version:

latest possible

### The latest.log file:

https://mclo.gs/dQIld5F

**Comment by Hantonik** [comment]
Hey,
It's hard to say exactly what's causing the error, but after looking at the log you sent, I see that several mods are having this issue. I think the problem might be with the **Mod Menu** mod.
