### ISSUE TITLE
[Bug] unable to work on hosted server part 

### ISSUE THREAD

**Issue by VaporeonScripts** [Hantonik/FancyBlockParticles#37]
### Issue description:

https://mclo.gs/RfwgBR1

### Steps to reproduce:

add the mod to server mods folder

### FBP version:

latest

### Minecraft version:

1.21

### Modloader version:

neoforge .72

### The latest.log file:

https://mclo.gs/RfwgBR1

**Comment by Hantonik** [comment]
Hi
There is no need to install this mod on the server, as it’s strictly client-side and won’t function on the server, as mentioned on its CurseForge or Modrinth page. 
**You can still have it installed on your client while connecting to the server without any issues.**

**Comment by VaporeonScripts** [comment]
I know,the mod should have the skip function like any other mod I see no reason for not adding it,see extreme sound muffler commit,or neo modlist

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/618dd2fa-a6fe-4d7b-983a-91bce6cbf203)
