### ISSUE TITLE
[Feature] 1.19.2 support?

### ISSUE THREAD

**Issue by QianFuv** [Hantonik/FancyBlockParticles#4]
### Feature description:

I believe version 1.19.2 will receive more attention than 1.19.4.

### Minecraft version:

Newer

### Modloader:

Forge

**Comment by Hantonik** [comment]
Hi, thanks for the suggestion!
I wasn't aware that version `1.19.2` is more popular than `1.19.4`, but after checking the download counts for the most popular mods on both versions, it seems to be accurate. Happy to learn!
Including support for version `1.19.2` sounds like a great idea!
