### ISSUE TITLE
[Bug] Crash when entering world

### ISSUE THREAD

**Issue by Karashok-Leo** [Hantonik/FancyBlockParticles#41]
### Issue description:

Crash happens when running with embeddium.

### Steps to reproduce:

Install FBP
Install Embeddium
Enter a world

### FBP version:

20.1.1.0 (newer version still crashes)

### Minecraft version:

1.20.1

### Modloader version:

Fabric 0.15.11

### The latest.log file:

[latest.log](https://github.com/user-attachments/files/17686502/latest.log)

**Comment by Hantonik** [comment]
Hi!
This bug has been fixed in the next mod version. However, I would highly recommend using **Sodium** over **Embeddium** on **Fabric** for better performance and stability.
