### ISSUE TITLE
Bug Report/Feature Request/Question

### ISSUE THREAD

**Issue by deadspidervenom** [Hantonik/FancyBlockParticles#5]
### Feature description:

Not really what this is, since i did not see a option in the config for it ima assume its a request.

Could i please get a option to disable block breaking particles? I really like the Ambient Particles for like weather and such, however the block breaking particles when combined with other mods causes MASSIVE lag. A example being HT's Treechop. If you chop down a large oak or bigger tree, every block breaks with particle effects. Which would look cool with the mod, but my frames go to 0. 

Oh i also wanted to say, if you made a version that was purely ambient particles you could advertise it to content creators, as the rain and snow particles default setting for vanilla makes recording and streaming quality take a nose dive.

### Minecraft version:

1.21

### Modloader:

NeoForge

**Comment by Hantonik** [comment]
Hey, thanks for the suggestion!
I've implemented the **Fancy block breaking** option in the FBP Options Menu. By toggling it off, you'll revert the block breaking particles to vanilla while keeping everything else intact, including **Fancy rain** and **Fancy snow** particles.
Hope that helps!
