### ISSUE TITLE
[Bug] java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by SebSemos** [Hantonik/FancyBlockParticles#9]
### Issue description:

Crash when transitioning rain vs snow with Fancy Rain off, and snow on.

Tested with FBP only

### Steps to reproduce:

Put fancy rain off in config
Keep fancy snow on
Find a taiga
Make it rain
Go up to get snow
Crash

### FBP version:

1.0.4.0-beta

### Minecraft version:

1.20.4

### Modloader:

Fabric

### Modloader version:

fabric-api-0.96.11+1.20.4

### The latest.log file:

[crash-2024-05-10_03.47.44-client.txt](https://github.com/Hantonik/FancyBlockParticles/files/15269378/crash-2024-05-10_03.47.44-client.txt)

**Comment by Hantonik** [comment]
Hey
After thoroughly rewriting the entire mod's code, I attempted to reproduce the bug you described. The error no longer occurs, so I'm marking the issue as resolved.
